defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

name: deneck_bridge
render: true
vis_debug: false
seed: 1
max_env_steps: 50
env:
  _target_: vtamp.environments.bridge.env.BridgeEnv
  stability_check: False
  gui: true
task:
  _target_: vtamp.environments.bridge.env.BuildPlanarI
  goal_str: "Build a planar roman numeral I"
  task_name: BuildPlanarI
policy:
  _target_: vtamp.policies.DENECK.policy.DENECK
  max_feedbacks: 0
  max_csp_samples: 10000
  gaussian_blur: false
  method: deneck
updater:
  _target_: vtamp.environments.utils.DefaultUpdater