defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

name: deneck_bridge
render: true
vis_debug: false
seed: 1
use_komo: false
max_env_steps: 50
env:
  _target_: vtamp.environments.bridge.env.BridgeEnv
  stability_check: False
  gui: true
task:
  _target_: vtamp.environments.bridge.tasks.PushRed
  goal_str: "Push the red block to the taget pose."
  task_name: PushRed
policy:
  _target_: vtamp.policies.ours.policy.Ours
  max_feedbacks: 0
  max_csp_samples: 10000
  gaussian_blur: false
  method: ours
updater:
  _target_: vtamp.environments.utils.DefaultUpdater