defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

name: proc3s_triangle
render: true
vis_debug: false
seed: 10
max_env_steps: 50
env:
  _target_: vtamp.environments.bridge.env.BridgeEnv
  stability_check: False
  gui: true
task:
  _target_: vtamp.environments.bridge.tasks.BuildPlanarTriangle
  goal_str: "Build a triangle"
  task_name: BuildPlanarTriangle
policy:
  _target_: vtamp.policies.ours.policy.Ours
  max_feedbacks: 5
  max_csp_samples: 10000
  gaussian_blur: false
  method: ours
updater:
  _target_: vtamp.environments.utils.DefaultUpdater